language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head

before_install:
  - yes | gem update --system
  - gem install bundler -v "~> 2.0"

script: bundle exec rspec spec

jobs:
  allow_failures:
    - rvm: ruby-head

services:
    - redis-server
